CREATE TABLE STG_VW_DADOSRH (
    ID_PESSOA               NUMBER(10) NOT NULL,
    NOME                    VARCHAR2(255),
    MATRICULA               VARCHAR2(255),
    CPF                     VARCHAR2(255),
    EMAIL                   VARCHAR2(255),
    EXERCICIO               VARCHAR2(255),
    INICIOCOLOCACAO        DATE,
    FIMCOLOCACAO           DATE,
    SITUACAOFUNCIONAL      VARCHAR2(255),
    DATASITUACAOFUNCIONAL DATE,
    VAGA                    NUMBER(10),
    CARGO                   VARCHAR2(255),
    TIPOCARGO              VARCHAR2(255),
    LOTACAO                 VARCHAR2(255),
    ATIVO                   NUMBER(10),
    ID_TIPOCARGO           NUMBER(10),
    PADRAO                  VARCHAR2(255),
    CLASSE                  VARCHAR2(255),
    INICIOPADRAO           DATE,
    FIMPADRAO              DATE,
    ID_CARGO                NUMBER(10),
    FREQUENCIA              VARCHAR2(255),
    NASCIMENTO              DATE,
    MAE                     VARCHAR2(255),
    ID_UORG                 NUMBER(10),
    ID_INSTITUICAO          NUMBER(10),
    CARGONIVEL             VARCHAR2(255)
);
