CREATE TABLE STG_TBTECNICO (
    IDTECNICO NUMBER NOT NULL,
    TECNICONOME VARCHAR2(255),
    TECNICOMATRICULA VARCHAR2(255),
    TECNICOCARGO VARCHAR2(255),
    TECNICOORGAO VARCHAR2(255),
    TECNICOEMAIL VARCHAR2(255),
    TECNICOFONE VARCHAR2(255),
    TECNICOCELULAR VARCHAR2(255)
);
