-- 0. Cria uma tabela temporária para guardar o Id da campanha.
-- O conceito de campanha não existia no SQL Server.
BEGIN
  EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE TEMP_CAMPANHA_MAP (
     IDVISTORIA NUMBER,
     CAM_CD      NUMBER
  ) ON COMMIT DELETE ROWS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 1. Insere uma campanha por vistoria (distinct IdVistoria) e guarda o Id da Campanha.
DECLARE
  CURSOR cur_v IS
    SELECT DISTINCT v.IDVISTORIA,
           v.IDCAMPANHA,
           v.IDTIPOVISTORIA,
           v.VISTORIADATAINICIO,
           v.VISTORIADATAFIM,
           v.VISTORIAFINALIDADE,
           v.NUMEROPROTON,
           b.CODIGO_SNISB
      FROM STG_TBVISTORIA v
      JOIN STG_VW_BDBARRAGEM b
        ON v.IDBARRAGEM = b.IDBARRAGEM;
  l_bar_cd SNISSBARRAGENS@ORAHMG_LINK.BAR_CD%TYPE;
  l_cam_cd NUMBER;
BEGIN
  FOR r IN cur_v LOOP
    BEGIN
      SELECT n.BAR_CD
        INTO l_bar_cd
        FROM SNISSBARRAGENS@ORAHMG_LINK n
       WHERE n.BAR_CD_SNISB = r.CODIGO_SNISB;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      l_bar_cd := NULL;
    END;
    -- insere uma campanha para esta vistoria
    INSERT INTO FISCALIZACAO_MIGRACAO.FISTB_CAMPANHA (
      CAM_CD,
      CAM_TSC_CD,
      CAM_TCA_CD,
      CAM_BAC_CD,
      CAM_SER_RES_CD,
      CAM_SER_AUX_CD,
      CAM_NU_ANO,
      CAM_NU,
      CAM_DT_INICIO,
      CAM_DT_FIM,
      CAM_DS_FINALIDADE,
      CAM_NU_RELATORIO,
      CAM_NU_NOTATECNICAPROTON,
      CAM_NM,
      CAM_NU_DOC_RELATORIO,
      CAM_NU_DOC_NOTATECNICA,
      CAM_IC_BARRAGEM
    ) VALUES (
      FISTB_CAMPANHA_SEQ.NEXTVAL,
      1,
      r.IDTIPOVISTORIA,
      l_bar_cd,
      NULL,
      NULL,
      TO_NUMBER(SUBSTR(r.IDCAMPANHA,1,4)),
      TO_NUMBER(SUBSTR(r.IDCAMPANHA,6)),
      r.VISTORIADATAINICIO,
      r.VISTORIADATAFIM,
      SUBSTR(r.VISTORIAFINALIDADE,1,500),
      NULL,
      r.NUMEROPROTON,
      r.IDCAMPANHA,
      NULL,
      r.NUMEROPROTON,
      1
    ) RETURNING CAM_CD INTO l_cam_cd;

    -- guarda o Id da campanha
    INSERT INTO TMP_CAMPAIGN_MAP (IDVISTORIA, CAM_CD)
    VALUES (r.IDVISTORIA, l_cam_cd);
  END LOOP;
END;
/

-- 2. Insere TbVistoria em FISTB_VISTORIA_BARRAGEM usando o Id da
--    campanha gerado anteriormente e o BAR_CD obtido da view com
--    código SNISB
INSERT INTO FISCALIZACAO_MIGRACAO.FISTB_VISTORIA_BARRAGEM (
  VIB_CD,
  VIB_BAR_CD,
  VIB_CAM_CD,
  VIB_NU,
  VIB_DT,
  VIB_DS_PROVIDENCIAS,
  VIB_DS_RECOMENDACOES,
  VIB_SVI_CD,
  VIB_NU_RELVISTORIA
)
SELECT
  FISTB_VISTORIA_BARRAGEM_SEQ.NEXTVAL,
  n.BAR_CD,
  m.CAM_CD,
  v.IDVISTORIA,
  v.VISTORIADATAINICIO,
  SUBSTR(v.VISTORIARECOMENDACAO,1,500),
  SUBSTR(v.VISTORIARECOMENDACAOPV,1,500),
  v.IDSITUACAOVISTORIA,
  v.NUMEROPROTON
FROM STG_TBVISTORIA v
JOIN TMP_CAMPAIGN_MAP m
  ON v.IDVISTORIA = m.IDVISTORIA
JOIN STG_VW_BDBARRAGEM b
  ON v.IDBARRAGEM = b.IDBARRAGEM
LEFT JOIN SNISSBARRAGENS@ORAHMG_LINK n
  ON b.CODIGO_SNISB = n.BAR_CD_SNISB
WHERE NOT EXISTS (
  SELECT 1 FROM FISCALIZACAO_MIGRACAO.FISTB_VISTORIA_BARRAGEM b2
   WHERE b2.VIB_NU = v.IDVISTORIA
);

-- 3. Insere TbOcorrencia em FISTB_OCORRENCIA
INSERT INTO FISCALIZACAO_MIGRACAO.FISTB_OCORRENCIA (
  OCO_CD,
  OCO_EMR_CD,
  OCO_EMI_CD,
  OCO_TOC_CD,
  OCO_TX_EMPREENDIMENTOMOMENTO,
  OCO_DT_OCORRENCIA,
  OCO_IC_TEMPROCESSO,
  OCO_NU_PROCESSO,
  OCO_TSO_CD,
  OCO_NU_PROTOCOLO,
  OCO_DT_RECEBIMENTOAR,
  OCO_DT_VENCIMENTOOCORRENCIA,
  OCO_IC_MIGRADO,
  OCO_DT_VENCIMENTOORIGINAL,
  OCO_IC_EXCLUIDO,
  OCO_BAR_CD
)
SELECT
  FISTB_OCORRENCIA_SEQ.NEXTVAL,
  s.IDBARRAGEM,
  NULL,
  s.IDTIPOOCORRENCIA,
  SUBSTR(s.OCORRENCIADESCRICAO,1,4000),
  s.OCORRENCIADATAINICIO,
  CASE WHEN s.OCORRENCIANUMEROPROCESSO IS NOT NULL THEN 1 ELSE 0 END,
  s.OCORRENCIANUMEROPROCESSO,
  s.IDSITUACAOOCORRENCIA,
  s.OCORRENCIANUMERODOC,
  s.OCORRENCIADATASITUACAO,
  s.OCORRENCIADATAFINAL,
  0,
  s.OCORRENCIADATAFINALMULTA,
  0,
  n2.BAR_CD
FROM STG_TBOCORRENCIA s
JOIN STG_VW_BDBARRAGEM b2
  ON s.IDBARRAGEM = b2.IDBARRAGEM
LEFT JOIN SNISSBARRAGENS@ORAHMG_LINK n2
  ON b2.CODIGO_SNISB = n2.BAR_CD_SNISB
WHERE NOT EXISTS (
  SELECT 1 FROM FISCALIZACAO_MIGRACAO.FISTB_OCORRENCIA o
   WHERE o.OCO_NU_PROTOCOLO = s.OCORRENCIANUMERODOC
);

-- 4. Gera um registro em FISTB_INSTRUMENTOFISCALIZACAO linkando
--    campanha, vistoria e ocorrência usando o CAM_CD mapeado na
--    tabela temporária.
INSERT INTO FISCALIZACAO_MIGRACAO.FISTB_INSTRUMENTOFISCALIZACAO (
  AUI_CD,
  AUI_OCO_CD,
  AUI_TAL_CD,
  AUI_TPR_CD,
  AUI_CAM_CD,
  AUI_CD_REFERENCIA,
  AUI_DS_SITUACAO,
  AUI_DS_NOTIFICADOA,
  AUI_VL_PRAZOPROVIDENCIA,
  AUI_IC_PRAZOIMEDIATO,
  AUI_NM_SERVIDOR,
  AUI_NU_SIAPE,
  AUI_NU_RASTREAMENTOAR,
  AUI_IC_ASSOCIADOCAMPANHA,
  AUI_DT_RECEBIMENTOAR,
  AUI_NU_DOCUMENTOREFERENCIA,
  AUI_IC_VINCULACAOAUIANTERIOR,
  AUI_NU_INSTRUMENTO,
  AUI_DT_LAVRATURA
)
SELECT
  FISTB_INSTRUMENTOFISCALIZACAO_SEQ.NEXTVAL,
  o.OCO_CD,
  NULL,
  NULL,
  m.CAM_CD,
  s.OCORRENCIANUMERODOCREF,
  SUBSTR(s.OCORRENCIAPROVIDENCIAS,1,2000),
  t.TECNICONOME,
  s.OCORRENCIAPRAZO,
  0,
  t.TECNICONOME,
  t.TECNICOMATRICULA,
  s.OCORRENCIANUMEROAR,
  1,
  s.DTDOCUMENTO,
  s.OCORRENCIANUMERODOCREF,
  0,
  s.OCORRENCIANUMERODOC,
  s.DTDOCUMENTO
FROM STG_TBOCORRENCIA s
JOIN STG_TBVISTORIA v2
  ON s.IDVISTORIA = v2.IDVISTORIA
JOIN TMP_CAMPAIGN_MAP m
  ON v2.IDVISTORIA = m.IDVISTORIA
JOIN FISCALIZACAO_MIGRACAO.FISTB_OCORRENCIA o
  ON o.OCO_NU_PROTOCOLO = s.OCORRENCIANUMERODOC
LEFT JOIN STG_TBTECNICO t
  ON s.IDTECNICO = t.IDTECNICO
WHERE NOT EXISTS (
  SELECT 1 FROM FISCALIZACAO_MIGRACAO.FISTB_INSTRUMENTOFISCALIZACAO i
   WHERE i.AUI_OCO_CD = o.OCO_CD
);



-- Regras; Experimentações.
-- FISTB_OCORRENCIA
INSERT INTO FISCALIZACAO.FISTB_OCORRENCIA (
    OCO_CD,
    OCO_EMI_CD,
    OCO_EMR_CD,
    OCO_TOC_CD,
    OCO_TX_EMPREENDIMENTOMOMENTO,
    OCO_DT_OCORRENCIA,
    OCO_IC_TEMPROCESSO,
    OCO_NU_PROCESSO,
    OCO_TSO_CD,
    OCO_NU_PROTOCOLO,
    OCO_DT_RECEBIMENTOAR,
    OCO_DT_VENCIMENTOOCORRENCIA,
    OCO_IC_MIGRADO,
    OCO_NU_MINUTA,
    OCO_DT_VENCIMENTOORIGINAL,
    OCO_IC_EXCLUIDO,
    OCO_BAR_CD
)
SELECT
    IDOCORRENCIA AS OCO_CD, -- Checar o Id, se deve ser migrado ou é gerado pelo banco
    NULL AS OCO_EMI_CD,
    NULL AS OCO_EMR_CD,
    1 AS OCO_TOC_CD, -- Ajuste conforme regra de negócio (Confirmar com Fábio): 1 - Instrumentos de fiscalização; 2 - Demandas de fiscalização. É TUDO 1, confirmado com Josimar.
    NULL AS OCO_TX_EMPREENDIMENTOMOMENTO,
    DTDOCUMENTO AS OCO_DT_OCORRENCIA,
    CASE WHEN OCORRENCIANUMERODOCREF IS NOT NULL THEN 1 ELSE 0 END AS OCO_IC_TEMPROCESSO,
    CASE WHEN OCORRENCIANUMERODOCREF IS NOT NULL THEN OCORRENCIANUMEROPROCESSO ELSE NULL END AS OCO_NU_PROCESSO,
    CASE
        WHEN IDSITUACAOOCORRENCIA = 1 THEN 1 -- de 'Enviada' para 'Enviada'
        WHEN IDSITUACAOOCORRENCIA = 2 THEN 2 -- de 'Pendência Técnica' para 'Pendência Técnica/Aceita'
        WHEN IDSITUACAOOCORRENCIA = 3 THEN 3 -- de 'Suspensa' para 'Suspensa'
        WHEN IDSITUACAOOCORRENCIA = 4 THEN 4 -- de 'Cancelada' para 'Cancelada/Negada'
        WHEN IDSITUACAOOCORRENCIA = 5 THEN 5 -- de 'Concluída/Arquivada' para 'Concluída'
        WHEN IDSITUACAOOCORRENCIA = 6 THEN 6 -- de 'Sem Pend. Téc. (Pend. Financeira)' para 'Sem Pend. Téc. (Pend. Financeira)'
        WHEN IDSITUACAOOCORRENCIA = 7 THEN 8 -- Verificar com fábio a obs. 'verificar' no De-Para para ocorrencia 7: de 'Aguardando Cadastro Proton' para 'Em edição'. Confirmado com Josimar.
        ELSE NULL -- demais casos, NULL. (Confirmado com Josimar, não pode ter NULL!!!! Verificar no banco todos os casos de IdSituacaoOcorrencia)
    END AS OCO_TSO_CD, 
    NULL AS OCO_NU_PROTOCOLO, -- /* TODO: Pesquisar número do protocolo PROTON pelo NUMEROPROTON ou OCORRENCIANUMEROPROCESSO */
    OCORRENCIADATAINICIO AS OCO_DT_RECEBIMENTOAR,
    OCORRENCIADATAFINAL AS OCO_DT_VENCIMENTOOCORRENCIA,
    1 AS OCO_IC_MIGRADO,
    NULL AS OCO_NU_MINUTA, -- /* TODO: Pesquisar minuta no PROTON pelo NUMEROPROTON ou OCORRENCIANUMEROPROCESSO */
    NULL AS OCO_DT_VENCIMENTOORIGINAL,
    0 AS OCO_IC_EXCLUIDO,
    NULL AS OCO_BAR_CD -- /* TODO: Pesquisar OCO_BAR_CD na SNISSBARRAGENS.SNBFT_BARRAGEM via DB_VW_BDBARRAGEM e IDBARRAGEM */
FROM
    FISCALIZACAO.STG_TBOCORRENCIA;

-- Ao gerar a ocorrencia precisa ser gerado um registro na tabela 
-- FISTB_INSTRUMENTOFISCALIZACAO
INSERT INTO FISCALIZACAO.FISTB_INSTRUMENTOFISCALIZACAO (
    AUI_CD,
    AUI_OCO_CD,
    AUI_TPR_CD,
    AUI_DS_SITUACAO,
    AUI_DS_NOTIFICADOA,
    AUI_VL_PRAZOPROVIDENCIA,
    AUI_IC_PRAZOIMEDIATO,
    AUI_NU_AUTOINFRACAO,
    AUI_IC_LAVRADOEMCAMPO,
    AUI_NU_RASTREAMENTOAR,
    AUI_IC_ASSOCIADOCAMPANHA,
    AUI_DT_RECEBIMENTOAR,
    AUI_SER_CD
)
SELECT
    IDOCORRENCIA AS AUI_CD, -- Ainda não está muito claro esses Ids; Checar.
    IDOCORRENCIA AS AUI_OCO_CD,
    IDTIPOOCORRENCIA AS AUI_TPR_CD,
    OCORRENCIAPROVIDENCIAS AS AUI_DS_SITUACAO,
    OCORRENCIADESCRICAO AS AUI_DS_NOTIFICADOA,
    OCORRENCIAPRAZO AS AUI_VL_PRAZOPROVIDENCIA,
    CASE WHEN OCORRENCIAPRAZO = 0 THEN 1 ELSE 0 END AS AUI_IC_PRAZOIMEDIATO,
    OCORRENCIANUMERODOC AS AUI_NU_AUTOINFRACAO, -- Verificar MESMO AUI CD - ?
    1 AS AUI_IC_LAVRADOEMCAMPO,
    OCORRENCIANUMEROAR AS AUI_NU_RASTREAMENTOAR,
    0 AS AUI_IC_ASSOCIADOCAMPANHA,
    OCORRENCIADATAINICIO AS AUI_DT_RECEBIMENTOAR,
    IDTECNICO AS AUI_SER_CD -- Buscar na tabela TBTecnico?
FROM
    FISCALIZACAO.STG_TBOCORRENCIA;
