-- !!! ATENÇãO !!!
-- Limpa o sistema de homologação para os dados de barragens pois tinha lixo duplicado lá:
-- Deleta tudo
DELETE FROM FISCALIZACAO.FISTB_DOCUMENTO
WHERE DOC_AUI_CD IN (
    SELECT AUI_CD
    FROM FISCALIZACAO.FISTB_INSTRUMENTOFISCALIZACAO
    WHERE AUI_CAM_CD IN (
        SELECT CAM_CD 
        FROM FISCALIZACAO.FISTB_CAMPANHA 
        WHERE CAM_IC_BARRAGEM = 1
    )
);

DELETE FROM FISCALIZACAO.FISTB_INSTRUMENTOFISCALIZACAO
WHERE AUI_CAM_CD IN (
    SELECT CAM_CD 
    FROM FISCALIZACAO.FISTB_CAMPANHA 
    WHERE CAM_IC_BARRAGEM = 1
);

DELETE FROM FISCALIZACAO.FISTB_INSTRUMENTOFISCALIZACAO
WHERE AUI_OCO_CD IN (
    SELECT OCO_CD 
    FROM FISCALIZACAO.FISTB_OCORRENCIA 
    WHERE OCO_IC_MIGRADO = 1
);

DELETE FROM FISCALIZACAO.FISTB_VISTORIA_BARRAGEM
WHERE VIB_CAM_CD IN (
    SELECT CAM_CD 
    FROM FISCALIZACAO.FISTB_CAMPANHA 
    WHERE CAM_IC_BARRAGEM = 1
);

DELETE FROM FISCALIZACAO.FISTB_CAMPANHA 
WHERE CAM_IC_BARRAGEM = 1;

DELETE FROM FISCALIZACAO.FISTB_OCORRENCIA
WHERE OCO_IC_MIGRADO = 1;

COMMIT;

-- 0. Dropa todas as tabelas
BEGIN
  FOR t IN (
    SELECT 'FISCALIZACAO_ETL_RW.TEMP_SNISB_MAP' AS table_name FROM DUAL UNION ALL
    SELECT 'FISCALIZACAO_ETL_RW.TEMP_CAMPANHA_MAP' FROM DUAL UNION ALL
    SELECT 'FISCALIZACAO_ETL_RW.TEMP_TECNICO_MAP' FROM DUAL UNION ALL
    SELECT 'FISCALIZACAO_ETL_RW.FISTB_CAMPANHA_TEMP' FROM DUAL UNION ALL
    SELECT 'FISCALIZACAO_ETL_RW.FISTB_VISTORIA_BARRAGEM_TEMP' FROM DUAL UNION ALL
    SELECT 'FISCALIZACAO_ETL_RW.FISTB_OCORRENCIA_TEMP' FROM DUAL UNION ALL
    SELECT 'FISCALIZACAO_ETL_RW.FISTB_INSTRUMENTOFISCALIZACAO_TEMP' FROM DUAL
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name;
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
    END;
  END LOOP;
END;

-- 1.Tabelas auxiliares 
-- Cria uma cópia das estruturas das tabelas
CREATE TABLE FISCALIZACAO_ETL_RW.FISTB_CAMPANHA_TEMP AS SELECT * FROM FISCALIZACAO.FISTB_CAMPANHA WHERE 1=0;
CREATE TABLE FISCALIZACAO_ETL_RW.FISTB_VISTORIA_BARRAGEM_TEMP AS SELECT * FROM FISCALIZACAO.FISTB_VISTORIA_BARRAGEM WHERE 1=0;
CREATE TABLE FISCALIZACAO_ETL_RW.FISTB_OCORRENCIA_TEMP AS SELECT * FROM FISCALIZACAO.FISTB_OCORRENCIA WHERE 1=0;
ALTER TABLE FISCALIZACAO_ETL_RW.FISTB_OCORRENCIA_TEMP ADD (IDOCORRENCIA NUMBER);
CREATE TABLE FISCALIZACAO_ETL_RW.FISTB_INSTRUMENTOFISCALIZACAO_TEMP AS SELECT * FROM FISCALIZACAO.FISTB_INSTRUMENTOFISCALIZACAO WHERE 1=0;

-- Cria uma tabela temporária para guardar o Id da campanha.
-- O conceito de campanha não existe nos dados do banco de origem.
CREATE TABLE FISCALIZACAO_ETL_RW.TEMP_CAMPANHA_MAP (
  CAM_CD NUMBER, -- Id das campanhas que a gente vai criar
  IDVISTORIA NUMBER,
  IDBARRAGEM NUMBER,
  IDCAMPANHA VARCHAR2(8) -- Vem da tabela vistoria do banco de origem
);

-- Cria uma tabela temporaria com o mapeamento BAR_CD <> BAR_CD_SNISB
-- Isso vem de um DBLINK que estava dando erro e assim descartamos as colunas desnecessarias
CREATE TABLE FISCALIZACAO_ETL_RW.TEMP_SNISB_MAP AS
SELECT BAR_CD, BAR_CD_SNISB
FROM SNISSBARRAGENS.SNBFT_BARRAGEM;

-- Cria uma tabela temporária para mapear IDTECNICO (STG_TBTECNICO) para ID_PESSOA (STG_VW_DADOSRH)
-- A ligação é feita pelo EMAIL -- Conforme solicitação do Josimar.
-- Mas alguns registros têm e-mail diferentes nas duas tabelas, então também casamos por nome.
-- Verifiquei que nas duas tabelas não tem homônimos.
-- Para deduplicar a tabela VW_DADOSRH aplicamos a mesma regra do sistema:
-- @NamedQuery(name="DadosRH.pesquisarServidoresPorId",
--  query = "SELECT distinct rh FROM DadosRH rh "
--  +" WHERE rh.dataSituacaoFuncional = (SELECT max(dataSituacaoFuncional) FROM DadosRH WHERE id = rh.id) AND "
--  + " rh.id = :id"),
CREATE TABLE FISCALIZACAO_ETL_RW.TEMP_TECNICO_MAP AS
-- Primeiro, match por email
SELECT 
  t.IDTECNICO,
  rh.ID_PESSOA
FROM FISCALIZACAO_ETL_RW.STG_TBTECNICO t
JOIN (
  SELECT ID_PESSOA, EMAIL
  FROM FISCALIZACAO_ETL_RW.STG_VW_DADOSRH
  WHERE EMAIL IS NOT NULL
  GROUP BY ID_PESSOA, EMAIL
) rh ON UPPER(TRIM(t.TECNICOEMAIL)) = UPPER(TRIM(rh.EMAIL))
WHERE t.TECNICOEMAIL IS NOT NULL
UNION
-- Segundo, match por nome (para os que não casaram por email)
SELECT 
  t.IDTECNICO,
  rh.ID_PESSOA
FROM FISCALIZACAO_ETL_RW.STG_TBTECNICO t
JOIN (
  SELECT ID_PESSOA, NOME
  FROM FISCALIZACAO_ETL_RW.STG_VW_DADOSRH
  WHERE EMAIL IS NOT NULL
  GROUP BY ID_PESSOA, NOME
) rh ON UPPER(TRIM(t.TECNICONOME)) = UPPER(TRIM(rh.NOME))
WHERE NOT EXISTS (
  SELECT 1 
  FROM FISCALIZACAO_ETL_RW.STG_VW_DADOSRH rh2 
  WHERE UPPER(TRIM(rh2.EMAIL)) = UPPER(TRIM(t.TECNICOEMAIL))
);

-- 2. Insere uma campanha por vistoria (uma por combinação única de IDBARRAGEM + IDCAMPANHA) 
-- e guarda o Id da Campanha.

-- Primeiro a gente gera os Ids das campanhas que vamos criar.
-- Cada vistoria pertence a uma campanha.
-- Uma mesma campanha pode ter mais de uma vistoria.
INSERT INTO FISCALIZACAO_ETL_RW.TEMP_CAMPANHA_MAP (CAM_CD, IDVISTORIA, IDBARRAGEM, IDCAMPANHA)
SELECT 
  (SELECT NVL(MAX(CAM_CD), 0) FROM FISCALIZACAO.FISTB_CAMPANHA) + DENSE_RANK() OVER (ORDER BY v.IDCAMPANHA) AS CAM_CD,
  v.IDVISTORIA,
  v.IDBARRAGEM,
  v.IDCAMPANHA
FROM FISCALIZACAO_ETL_RW.STG_TBVISTORIA v
JOIN FISCALIZACAO_ETL_RW.STG_VW_BDBARRAGEM b ON v.IDBARRAGEM = b.IDBARRAGEM; -- Filtra apenas as barragens operadas pela ANA.

-- Cria as campanhas utilizando o mapeamento dos Ids previamente criados
INSERT INTO FISCALIZACAO_ETL_RW.FISTB_CAMPANHA_TEMP (
  CAM_CD,
  CAM_TSC_CD, -- 1. Prevista; 2. Andamento; 3. Suspensa; 4. Concluida; 5. Cancelada [Mapeamento bate com a origem]
  CAM_TCA_CD, -- 1. PAF; 2. Emergencial
  CAM_BAC_CD,
  CAM_SER_RES_CD,
  CAM_SER_AUX_CD,
  CAM_NU_ANO,
  CAM_NU,
  CAM_DT_INICIO,
  CAM_DT_FIM,
  CAM_DS_FINALIDADE,
  CAM_NU_RELATORIO,
  CAM_NU_NOTATECNICAPROTON,
  CAM_NM,
  CAM_NU_DOC_RELATORIO,
  CAM_NU_DOC_NOTATECNICA,
  CAM_IC_MIGRADO,
  CAM_IC_BARRAGEM
)
SELECT 
  c.CAM_CD, -- CAM_CD
  c.IDSITUACAOVISTORIA, -- CAM_TSC_CD -- 1. Prevista; 2. Andamento; 3. Suspensa; 4. Concluida; 5. Cancelada
  1, -- CAM_TCA_CD -- 1. PAF; 2. Emergencial
  NULL, -- CAM_BAC_CD
  c.ID_PESSOA_TEC1, -- CAM_SER_RES_CD (mapeado de IDTECNICO1 para ID_PESSOA)
  c.ID_PESSOA_TEC2, -- CAM_SER_AUX_CD (mapeado de IDTECNICO2 para ID_PESSOA)
  TO_NUMBER(SUBSTR(c.IDCAMPANHA,1,4)),-- CAM_NU_ANO
  TO_NUMBER(SUBSTR(c.IDCAMPANHA,6)), -- CAM_NU
  c.VISTORIADATAINICIO, -- CAM_DT_INICIO
  c.VISTORIADATAFIM, -- CAM_DT_FIM
  SUBSTRB(c.VISTORIAFINALIDADE,1,500), -- CAM_DS_FINALIDADE
  NULL, -- CAM_NU_RELATORIO
  NULL, -- CAM_NU_NOTATECNICAPROTON
  SUBSTR(c.IDCAMPANHA,6) || '/' || SUBSTR(c.IDCAMPANHA,1,4), -- CAM_NM
  NULL, -- CAM_NU_DOC_RELATORIO
  NULL, -- CAM_NU_DOC_NOTATECNICA
  1, -- CAM_IC_MIGRADO
  1 -- CAM_IC_BARRAGEM
FROM (
  SELECT 
    m.CAM_CD,
    m.IDCAMPANHA,
    MIN(v.VISTORIADATAINICIO) AS VISTORIADATAINICIO,
    MIN(v.IDSITUACAOVISTORIA) KEEP (DENSE_RANK FIRST ORDER BY v.VISTORIADATAINICIO) AS IDSITUACAOVISTORIA, -- Nas campanhas que se repetem na tabela vistoria consideramos as informações
    MIN(v.VISTORIAFINALIDADE) KEEP (DENSE_RANK FIRST ORDER BY v.VISTORIADATAINICIO) AS VISTORIAFINALIDADE, -- da primeira vistoria, ou seja, quando a campanha foi criada.
    MAX(v.VISTORIADATAFIM) AS VISTORIADATAFIM,
    MIN(tm1.ID_PESSOA) KEEP (DENSE_RANK FIRST ORDER BY v.VISTORIADATAINICIO) AS ID_PESSOA_TEC1,
    MIN(tm2.ID_PESSOA) KEEP (DENSE_RANK FIRST ORDER BY v.VISTORIADATAINICIO) AS ID_PESSOA_TEC2
  FROM FISCALIZACAO_ETL_RW.TEMP_CAMPANHA_MAP m
  JOIN FISCALIZACAO_ETL_RW.STG_TBVISTORIA v ON m.IDVISTORIA = v.IDVISTORIA
  LEFT JOIN FISCALIZACAO_ETL_RW.TEMP_TECNICO_MAP tm1 ON v.IDTECNICO1 = tm1.IDTECNICO
  LEFT JOIN FISCALIZACAO_ETL_RW.TEMP_TECNICO_MAP tm2 ON v.IDTECNICO2 = tm2.IDTECNICO
  GROUP BY m.CAM_CD, m.IDCAMPANHA
) c;

-- 3. Insere TbVistoria em FISTB_VISTORIA_BARRAGEM usando o Id da
-- campanha gerado anteriormente e o BAR_CD obtido da view com
-- código SNISB
INSERT INTO FISCALIZACAO_ETL_RW.FISTB_VISTORIA_BARRAGEM_TEMP (
  VIB_CD,
  VIB_BAR_CD,
  VIB_CAM_CD,
  VIB_NU,
  VIB_DT,
  VIB_DS_PROVIDENCIAS,
  VIB_DS_RECOMENDACOES,
  VIB_SVI_CD, -- 1. Prevista; 2. Concluída; 3. Cancelada
  VIB_NU_RELVISTORIA
)
SELECT
  (SELECT NVL(MAX(VIB_CD), 0) FROM FISCALIZACAO.FISTB_VISTORIA_BARRAGEM) + ROW_NUMBER() OVER (ORDER BY v.IDVISTORIA) AS VIB_CD, -- VIB_CD
  n.BAR_CD, -- VIB_BAR_CD
  m.CAM_CD, -- VIB_CAM_CD
  v.IDVISTORIA, -- VIB_NU
  v.VISTORIADATAINICIO, -- VIB_DT
  SUBSTRB(v.VISTORIARECOMENDACAO,1,500), -- VIB_DS_PROVIDENCIAS
  SUBSTRB(v.VISTORIARECOMENDACAOPV,1,500), -- VIB_DS_RECOMENDACOES
  CASE
        WHEN v.IDSITUACAOVISTORIA = 1 THEN 1 -- de 'Prevista' para 'Prevista'
        WHEN v.IDSITUACAOVISTORIA = 4 THEN 2 -- de 'Concluída' para 'Concluída'
        WHEN v.IDSITUACAOVISTORIA = 5 THEN 3 -- de 'Cancelada' para 'Cancelada'
        ELSE NULL -- demais casos, NULL. (Acho que não pode ter NULL!!!! Mas NULL não deve ocorrer pois confirmei no banco que só há casos 4 e 5)
    END AS VIB_SVI_CD,  -- VIB_SVI_CD
  v.NUMEROPROTON -- VIB_NU_RELVISTORIA
FROM FISCALIZACAO_ETL_RW.STG_TBVISTORIA v
JOIN FISCALIZACAO_ETL_RW.TEMP_CAMPANHA_MAP m ON v.IDVISTORIA = m.IDVISTORIA
JOIN FISCALIZACAO_ETL_RW.STG_VW_BDBARRAGEM b ON v.IDBARRAGEM = b.IDBARRAGEM
LEFT JOIN FISCALIZACAO_ETL_RW.TEMP_SNISB_MAP n ON b.CODIGO_SNISB = n.BAR_CD_SNISB;

-- 4. Insere TbOcorrencia em FISTB_OCORRENCIA
INSERT INTO FISCALIZACAO_ETL_RW.FISTB_OCORRENCIA_TEMP (
  OCO_CD,
  OCO_EMI_CD,
  OCO_EMR_CD,
  OCO_TOC_CD,
  OCO_TX_EMPREENDIMENTOMOMENTO,
  OCO_DT_OCORRENCIA,
  OCO_IC_TEMPROCESSO,
  OCO_NU_PROCESSO,
  OCO_TSO_CD,
  OCO_NU_PROTOCOLO,
  OCO_DT_RECEBIMENTOAR,
  OCO_DT_VENCIMENTOOCORRENCIA,
  OCO_IC_MIGRADO,
  OCO_NU_MINUTA,
  OCO_DT_VENCIMENTOORIGINAL,
  OCO_IC_EXCLUIDO,
  OCO_BAR_CD,
  IDOCORRENCIA
)
SELECT
  (SELECT NVL(MAX(OCO_CD), 0) FROM FISCALIZACAO.FISTB_OCORRENCIA) + ROW_NUMBER() OVER (ORDER BY s.IDOCORRENCIA), -- OCO_CD
  NULL, -- OCO_EMI_CD (Empreendimento Irregular)
  NULL, -- OCO_EMR_CD (Empreendimento Regular)
  1, -- OCO_TOC_CD (Tipo Ocorrencia): 1. Instrumento Fiscalização; 2. Demandas de Fiscalização
  NULL, -- OCO_TX_EMPREENDIMENTOMOMENTO
  s.OCORRENCIADATAINICIO, -- OCO_DT_OCORRENCIA
  CASE WHEN s.OCORRENCIANUMEROPROCESSO IS NOT NULL THEN 1 ELSE 0 END, -- OCO_IC_TEMPROCESSO
  s.OCORRENCIANUMEROPROCESSO, -- OCO_NU_PROCESSO
  CASE
        WHEN s.IDSITUACAOOCORRENCIA = 1 THEN 1 -- de 'Enviada' para 'Enviada'
        WHEN s.IDSITUACAOOCORRENCIA = 2 THEN 2 -- de 'Pendência Técnica' para 'Pendência Técnica/Aceita'
        WHEN s.IDSITUACAOOCORRENCIA = 3 THEN 3 -- de 'Suspensa' para 'Suspensa'
        WHEN s.IDSITUACAOOCORRENCIA = 4 THEN 4 -- de 'Cancelada' para 'Cancelada/Negada'
        WHEN s.IDSITUACAOOCORRENCIA = 5 THEN 5 -- de 'Concluída/Arquivada' para 'Concluída'
        WHEN s.IDSITUACAOOCORRENCIA = 6 THEN 6 -- de 'Sem Pend. Téc. (Pend. Financeira)' para 'Sem Pend. Téc. (Pend. Financeira)'
        WHEN s.IDSITUACAOOCORRENCIA = 7 THEN 8 -- Verificar com Fábio a obs. 'verificar' no De-Para para ocorrencia 7: de 'Aguardando Cadastro Proton' para 'Em edição'. Confirmado com Josimar.
        ELSE NULL -- demais casos, NULL. (Confirmado com Josimar, não pode ter NULL!!!! Verificar no banco todos os casos de IdSituacaoOcorrencia)
    END AS OCO_TSO_CD, -- OCO_TSO_CD
  NULL, -- OCO_NU_PROTOCOLO
  NULL, -- OCO_DT_RECEBIMENTOAR
  NULL, -- OCO_DT_VENCIMENTOOCORRENCIA
  1, -- OCO_IC_MIGRADO
  NULL, -- OCO_NU_MINUTA
  NULL, -- OCO_DT_VENCIMENTOORIGINAL
  0, -- OCO_IC_EXCLUIDO
  n.BAR_CD, -- OCO_BAR_CD
  s.IDOCORRENCIA -- IDOCORRENCIA
FROM FISCALIZACAO_ETL_RW.STG_TBOCORRENCIA s
JOIN FISCALIZACAO_ETL_RW.STG_VW_BDBARRAGEM b ON s.IDBARRAGEM = b.IDBARRAGEM
LEFT JOIN FISCALIZACAO_ETL_RW.TEMP_SNISB_MAP n ON b.CODIGO_SNISB = n.BAR_CD_SNISB;

-- 5. Gera um registro em FISTB_INSTRUMENTOFISCALIZACAO linkando
--    campanha, vistoria e ocorrência usando o CAM_CD mapeado na
--    tabela temporária. Se o IDVISTORIA na OCORRENCIA for NULL, 
--    AUI_CAM_CD entra como NULL (sem campanha).
INSERT INTO FISCALIZACAO_ETL_RW.FISTB_INSTRUMENTOFISCALIZACAO_TEMP (
  AUI_CD,
  AUI_OCO_CD,
  AUI_TAL_CD,
  AUI_TPR_CD,
  AUI_CAM_CD,
  AUI_CD_REFERENCIA,
  AUI_DS_SITUACAO,
  AUI_DS_NOTIFICADOA,
  AUI_VL_PRAZOPROVIDENCIA,
  AUI_IC_PRAZOIMEDIATO,
  AUI_NU_LOCAL_IBGEMUNICIPIO,
  AUI_NM_SERVIDOR,
  AUI_NU_SIAPE,
  AUI_NU_AUTOINFRACAO,
  AUI_IC_LAVRADOEMCAMPO,
  AUI_NU_RASTREAMENTOAR,
  AUI_IC_ASSOCIADOCAMPANHA,
  AUI_DT_RECEBIMENTOAR,
  AUI_NU_DOCUMENTOREFERENCIA,
  AUI_IC_VINCULACAOAUIANTERIOR,
  AUI_TIF_CD,
  AUI_SER_CD,
  AUI_NU_LACRE,
  AUI_TIR_CD,
  AUI_NU_CPF_SERVIDOR,
  AUI_NU_INSTRUMENTO,
  AUI_DT_LAVRATURA,
  AUI_IC_ATENUANTE,
  AUI_IC_AGRAVANTE,
  AUI_IC_TEXTOUM,
  AUI_IC_TEXTODOIS,
  AUI_IC_TEXTOTRES,
  AUI_IC_TEXTOQUATRO,
  AUI_IC_TEXTOCINCO,
  AUI_IC_TEXTUM,
  AUI_IC_TEXTDOIS,
  AUI_IC_TEXTTRES,
  AUI_IC_TEXTQUATRO,
  AUI_IC_TEXTCINCO,
  AUI_IC_TEXTSEIS,
  AUI_IC_TEXTSETE,
  AUI_IC_TEXTOITO,
  AUI_IC_TEXTNOVE,
  AUI_IC_TEXTDEZ
)
SELECT
  (SELECT NVL(MAX(AUI_CD), 0) FROM FISCALIZACAO.FISTB_INSTRUMENTOFISCALIZACAO) + ROW_NUMBER() OVER (ORDER BY s.IDOCORRENCIA), -- AUI_CD
  o.OCO_CD, -- AUI_OCO_CD (Id da ocorrencia FISTB_OCORRENCIA)
  NULL, -- AUI_TAL_CD
  CASE
    WHEN s.IDTIPOOCORRENCIA = 1 THEN 1 -- de 'AI - Advertência' para 'Advertência'
    WHEN s.IDTIPOOCORRENCIA = 2 THEN 2 -- de 'AI  - Multa Simples' para 'Multa Simples'
    WHEN s.IDTIPOOCORRENCIA = 3 THEN 3 -- de 'AI  - Multa Diária' para 'Multa Diária'
    WHEN s.IDTIPOOCORRENCIA = 4 THEN 4 -- de 'AI - Embargo Provisório' para 'Embargo Provisório'
    WHEN s.IDTIPOOCORRENCIA = 24 THEN 5 -- de 'AI - Embargo Definitivo' para 'Embargo Definitivo'
    WHEN s.IDTIPOOCORRENCIA IN (25, 5) THEN NULL -- Notificação e Solic. Providências
    ELSE NULL -- demais casos, NULL
  END AS AUI_TPR_CD, -- AUI_TPR_CD
  m.CAM_CD, -- AUI_CAM_CD
  NULL, -- AUI_CD_REFERENCIA
  SUBSTRB(s.OCORRENCIAPROVIDENCIAS,1,2000), -- AUI_DS_SITUACAO
  SUBSTRB(s.OCORRENCIADESCRICAO,1,2000), -- AUI_DS_NOTIFICADOA
  CASE
    WHEN s.OCORRENCIAPRAZO > 999 THEN 999
    ELSE s.OCORRENCIAPRAZO 
  END AS AUI_VL_PRAZOPROVIDENCIA, -- AUI_VL_PRAZOPROVIDENCIA
  0, -- AUI_IC_PRAZOIMEDIATO
  NULL, -- AUI_NU_LOCAL_IBGEMUNICIPIO
  NULL, -- AUI_NM_SERVIDOR
  NULL, -- AUI_NU_SIAPE
  1, -- AUI_NU_AUTOINFRACAO (OcorrenciaNumeroDoc ???)
  1, -- AUI_IC_LAVRADOEMCAMPO (Toda a importação vai ser auto lavrado em campo)
  SUBSTRB(s.OCORRENCIANUMEROAR, 1, 45), -- AUI_NU_RASTREAMENTOAR
  0, -- AUI_IC_ASSOCIADOCAMPANHA
  s.OCORRENCIADATAINICIO, -- AUI_DT_RECEBIMENTOAR
  NULL, -- AUI_NU_DOCUMENTOREFERENCIA
  NULL, -- AUI_IC_VINCULACAOAUIANTERIOR
  CASE
    WHEN s.IDTIPOOCORRENCIA IN (1, 2, 3, 4, 24) THEN 1 -- AI - Auto de Infração
    WHEN s.IDTIPOOCORRENCIA IN (25, 5) THEN 3 -- Notificação
    ELSE NULL
  END AS AUI_TIF_CD, -- AUI_TIF_CD
  tm.ID_PESSOA, -- AUI_SER_CD (mapeado de IDTECNICO para ID_PESSOA)
  NULL, -- AUI_NU_LACRE
  NULL, -- AUI_TIR_CD
  NULL, -- AUI_NU_CPF_SERVIDOR
  NULL, -- AUI_NU_INSTRUMENTO
  NULL, -- AUI_DT_LAVRATURA
  NULL, -- AUI_IC_ATENUANTE
  NULL, -- AUI_IC_AGRAVANTE
  NULL, -- AUI_IC_TEXTOUM
  NULL, -- AUI_IC_TEXTODOIS
  NULL, -- AUI_IC_TEXTOTRES
  NULL, -- AUI_IC_TEXTOQUATRO
  NULL, -- AUI_IC_TEXTOCINCO
  NULL, -- AUI_IC_TEXTUM
  NULL, -- AUI_IC_TEXTDOIS
  NULL, -- AUI_IC_TEXTTRES
  NULL, -- AUI_IC_TEXTQUATRO
  NULL, -- AUI_IC_TEXTCINCO
  NULL, -- AUI_IC_TEXTSEIS
  NULL, -- AUI_IC_TEXTSETE
  NULL, -- AUI_IC_TEXTOITO
  NULL, -- AUI_IC_TEXTNOVE
  NULL  -- AUI_IC_TEXTDEZ
FROM FISCALIZACAO_ETL_RW.STG_TBOCORRENCIA s
JOIN FISCALIZACAO_ETL_RW.FISTB_OCORRENCIA_TEMP o ON o.IDOCORRENCIA = s.IDOCORRENCIA
LEFT JOIN FISCALIZACAO_ETL_RW.TEMP_CAMPANHA_MAP m ON s.IDVISTORIA = m.IDVISTORIA
LEFT JOIN FISCALIZACAO_ETL_RW.TEMP_TECNICO_MAP tm ON s.IDTECNICO = tm.IDTECNICO
WHERE s.IDTIPOOCORRENCIA != 7; -- Descarta registros do tipo 'Protocolo Emergência' (Essas barragens não mais fiscalizadas pela ANA segundo o Josimar)

-- 6. Cópia das tabelas temporárias para as tabelas finais
INSERT INTO FISCALIZACAO.FISTB_CAMPANHA
SELECT
  CAM_CD, CAM_TSC_CD, CAM_TCA_CD, CAM_BAC_CD, CAM_SER_RES_CD, CAM_SER_AUX_CD,
  CAM_NU_ANO, CAM_NU, CAM_DT_INICIO, CAM_DT_FIM, CAM_DS_FINALIDADE,
  CAM_NU_RELATORIO, CAM_NU_NOTATECNICAPROTON, CAM_NM, CAM_NU_DOC_RELATORIO,
  CAM_NU_DOC_NOTATECNICA, CAM_IC_MIGRADO, CAM_IC_BARRAGEM
FROM FISCALIZACAO_ETL_RW.FISTB_CAMPANHA_TEMP;

INSERT INTO FISCALIZACAO.FISTB_VISTORIA_BARRAGEM
SELECT
  VIB_CD, VIB_BAR_CD, VIB_CAM_CD, VIB_NU, VIB_DT, VIB_DS_PROVIDENCIAS,
  VIB_DS_RECOMENDACOES, VIB_SVI_CD, VIB_NU_RELVISTORIA
FROM FISCALIZACAO_ETL_RW.FISTB_VISTORIA_BARRAGEM_TEMP;

INSERT INTO FISCALIZACAO.FISTB_OCORRENCIA
SELECT
  OCO_CD, OCO_EMI_CD, OCO_EMR_CD, OCO_TOC_CD, OCO_TX_EMPREENDIMENTOMOMENTO,
  OCO_DT_OCORRENCIA, OCO_IC_TEMPROCESSO, OCO_NU_PROCESSO, OCO_TSO_CD,
  OCO_NU_PROTOCOLO, OCO_DT_RECEBIMENTOAR, OCO_DT_VENCIMENTOOCORRENCIA,
  OCO_IC_MIGRADO, OCO_NU_MINUTA, OCO_DT_VENCIMENTOORIGINAL,
  OCO_IC_EXCLUIDO, OCO_BAR_CD
FROM FISCALIZACAO_ETL_RW.FISTB_OCORRENCIA_TEMP;

INSERT INTO FISCALIZACAO.FISTB_INSTRUMENTOFISCALIZACAO
SELECT
  AUI_CD, AUI_OCO_CD, AUI_TAL_CD, AUI_TPR_CD, AUI_CAM_CD, AUI_CD_REFERENCIA,
  AUI_DS_SITUACAO, AUI_DS_NOTIFICADOA, AUI_VL_PRAZOPROVIDENCIA, AUI_IC_PRAZOIMEDIATO,
  AUI_NU_LOCAL_IBGEMUNICIPIO, AUI_NM_SERVIDOR, AUI_NU_SIAPE, AUI_NU_AUTOINFRACAO,
  AUI_IC_LAVRADOEMCAMPO, AUI_NU_RASTREAMENTOAR, AUI_IC_ASSOCIADOCAMPANHA,
  AUI_DT_RECEBIMENTOAR, AUI_NU_DOCUMENTOREFERENCIA, AUI_IC_VINCULACAOAUIANTERIOR,
  AUI_TIF_CD, AUI_SER_CD, AUI_NU_LACRE, AUI_TIR_CD, AUI_NU_CPF_SERVIDOR,
  AUI_NU_INSTRUMENTO, AUI_DT_LAVRATURA, AUI_IC_ATENUANTE, AUI_IC_AGRAVANTE,
  AUI_IC_TEXTOUM, AUI_IC_TEXTODOIS, AUI_IC_TEXTOTRES, AUI_IC_TEXTOQUATRO,
  AUI_IC_TEXTOCINCO, AUI_IC_TEXTUM, AUI_IC_TEXTDOIS, AUI_IC_TEXTTRES,
  AUI_IC_TEXTQUATRO, AUI_IC_TEXTCINCO, AUI_IC_TEXTSEIS, AUI_IC_TEXTSETE,
  AUI_IC_TEXTOITO, AUI_IC_TEXTNOVE, AUI_IC_TEXTDEZ
FROM FISCALIZACAO_ETL_RW.FISTB_INSTRUMENTOFISCALIZACAO_TEMP;

-- 7. Sincroniza as sequences
DECLARE
  l_max_value NUMBER;
  l_seq_exists NUMBER;
  l_current_value NUMBER;
  l_increment NUMBER;
  PROCEDURE sync_sequence(p_seq_name VARCHAR2, p_table_name VARCHAR2, p_column_name VARCHAR2) IS
  BEGIN
    -- Verifica se a sequencia existe.
    SELECT COUNT(*) INTO l_seq_exists
    FROM all_sequences
    WHERE sequence_name = p_seq_name;
    IF l_seq_exists = 0 THEN
      DBMS_OUTPUT.PUT_LINE('Sequence ' || p_seq_name || ' não existe. Skipping.');
      RETURN;
    END IF;
    -- Pega o valor máximo da tabela
    EXECUTE IMMEDIATE 'SELECT NVL(MAX(' || p_column_name || '), 0) FROM ' || p_table_name 
      INTO l_max_value;
    -- Pega o valor corrente da sequencia
    EXECUTE IMMEDIATE 'SELECT ' || p_seq_name || '.NEXTVAL FROM DUAL' 
      INTO l_current_value;
    -- Se a sequencia está para trás, atualiza
    IF l_current_value <= l_max_value THEN
      l_increment := l_max_value - l_current_value + 1;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || p_seq_name || ' INCREMENT BY ' || l_increment;
      EXECUTE IMMEDIATE 'SELECT ' || p_seq_name || '.NEXTVAL FROM DUAL' INTO l_current_value;
      EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || p_seq_name || ' INCREMENT BY 1';
      DBMS_OUTPUT.PUT_LINE(p_seq_name || ' sincronizada. Próximo valor: ' || l_current_value);
    ELSE
      DBMS_OUTPUT.PUT_LINE(p_seq_name || ' sequencia à frente. Valor corrente: ' || l_current_value || ', Valor max. na tabela: ' || l_max_value);
    END IF;
  END;
BEGIN
  sync_sequence('FISSQ_CAMPANHA', 'FISCALIZACAO.FISTB_CAMPANHA', 'CAM_CD');
  sync_sequence('FISSQ_VISTORIABARRAGEM', 'FISCALIZACAO.FISTB_VISTORIA_BARRAGEM', 'VIB_CD');
  sync_sequence('FISSQ_OCORRENCIA', 'FISCALIZACAO.FISTB_OCORRENCIA', 'OCO_CD');
  sync_sequence('FISSQ_INSTFISCALIZACAO', 'FISCALIZACAO.FISTB_INSTRUMENTOFISCALIZACAO', 'AUI_CD');
  DBMS_OUTPUT.PUT_LINE('Sequence sync completo!');
END;
