-- 0. Cria uma tabela temporária para guardar o Id da campanha.
-- O conceito de campanha não existe nos dados do SQL Server.
BEGIN
  EXECUTE IMMEDIATE 'CREATE GLOBAL TEMPORARY TABLE TEMP_CAMPANHA_MAP (
     IDVISTORIA NUMBER,
     CAM_CD      NUMBER
  ) ON COMMIT DELETE ROWS';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;

-- 1. Insere uma campanha por vistoria (distinct IdVistoria) e guarda o Id da Campanha.
DECLARE
  CURSOR cur_v IS
    SELECT DISTINCT v.IDVISTORIA,
           v.IDBARRAGEM,
           v.IDCAMPANHA,
           v.IDTIPOVISTORIA,
           v.IDSITUACAOVISTORIA,
           v.VISTORIADATAINICIO,
           v.VISTORIADATAFIM,
           v.VISTORIAFINALIDADE,
           v.NUMEROPROTON,
           b.CODIGO_SNISB
      FROM STG_TBVISTORIA v
      JOIN STG_VW_BDBARRAGEM b
        ON v.IDBARRAGEM = b.IDBARRAGEM;
  l_bar_cd NUMBER;
  l_cam_cd NUMBER;
BEGIN
  FOR r IN cur_v LOOP
    BEGIN
      SELECT n.BAR_CD
        INTO l_bar_cd
        FROM SNISSBARRAGENS.SNBFT_BARRAGEM@ORAHMG_LINK n
       WHERE n.BAR_CD_SNISB = r.CODIGO_SNISB;
    EXCEPTION WHEN NO_DATA_FOUND THEN
      l_bar_cd := NULL;
    END;
    -- insere uma campanha para esta vistoria
    INSERT INTO FISCALIZACAO_MIGRACAO.FISTB_CAMPANHA_TEMP (
      CAM_CD,
      CAM_TSC_CD, -- 1. Prevista; 2. Andamento; 3. Suspensa; 4. Concluida; 5. Cancelada
      CAM_TCA_CD, -- 1. PAF; 2. Emergencial
      CAM_BAC_CD,
      CAM_SER_RES_CD,
      CAM_SER_AUX_CD,
      CAM_NU_ANO,
      CAM_NU,
      CAM_DT_INICIO,
      CAM_DT_FIM,
      CAM_DS_FINALIDADE,
      CAM_NU_RELATORIO,
      CAM_NU_NOTATECNICAPROTON,
      CAM_NM,
      CAM_NU_DOC_RELATORIO,
      CAM_NU_DOC_NOTATECNICA,
      CAM_IC_MIGRADO,
      CAM_IC_BARRAGEM
    ) VALUES (
      FISSQ_CAMPANHA.NEXTVAL, -- CAM_CD
      r.IDSITUACAOVISTORIA, -- CAM_TSC_CD
      1, -- CAM_TCA_CD
      NULL, -- CAM_BAC_CD
      NULL, -- CAM_SER_RES_CD
      NULL, -- CAM_SER_AUX_CD
      TO_NUMBER(SUBSTR(r.IDCAMPANHA,1,4)), -- CAM_NU_ANO
      TO_NUMBER(SUBSTR(r.IDCAMPANHA,6)), -- CAM_NU
      r.VISTORIADATAINICIO, -- CAM_DT_INICIO
      r.VISTORIADATAFIM, -- CAM_DT_FIM
      SUBSTRB(r.VISTORIAFINALIDADE,1,500), -- CAM_DS_FINALIDADE
      NULL, -- CAM_NU_RELATORIO
      NULL, -- CAM_NU_NOTATECNICAPROTON
      SUBSTR(r.IDCAMPANHA,6) || '/' || SUBSTR(r.IDCAMPANHA,1,4), -- CAM_NM
      NULL, -- CAM_NU_DOC_RELATORIO
      NULL, -- CAM_NU_DOC_NOTATECNICA
      1, -- CAM_IC_MIGRADO
      1 -- CAM_IC_BARRAGEM
    ) RETURNING CAM_CD INTO l_cam_cd;

    -- guarda o Id da campanha
    INSERT INTO TEMP_CAMPANHA_MAP(IDVISTORIA, CAM_CD)
    VALUES (r.IDVISTORIA, l_cam_cd);
  END LOOP;
END;

-- 2. Insere TbVistoria em FISTB_VISTORIA_BARRAGEM usando o Id da
--    campanha gerado anteriormente e o BAR_CD obtido da view com
--    código SNISB
INSERT INTO FISCALIZACAO_MIGRACAO.FISTB_VISTORIA_BARRAGEM_TEMP (
  VIB_CD,
  VIB_BAR_CD,
  VIB_CAM_CD,
  VIB_NU,
  VIB_DT,
  VIB_DS_PROVIDENCIAS,
  VIB_DS_RECOMENDACOES,
  VIB_SVI_CD, -- 1. Prevista; 2. Concluída; 3. Cancelada
  VIB_NU_RELVISTORIA
)
SELECT
  FISSQ_VISTORIA_BARRAGEM.NEXTVAL, -- VIB_CD
  n.BAR_CD, -- VIB_BAR_CD
  m.CAM_CD, -- VIB_CAM_CD
  NULL, -- VIB_NU
  v.VISTORIADATAINICIO, -- VIB_DT
  SUBSTR(v.VISTORIARECOMENDACAO,1,500), -- VIB_DS_PROVIDENCIAS
  SUBSTR(v.VISTORIARECOMENDACAOPV,1,500), -- VIB_DS_RECOMENDACOES
  CASE
        WHEN v.IDSITUACAOVISTORIA = 1 THEN 1 -- de 'Prevista' para 'Prevista'
        WHEN v.IDSITUACAOVISTORIA = 4 THEN 2 -- de 'Concluída' para 'Concluída'
        WHEN v.IDSITUACAOVISTORIA = 5 THEN 3 -- de 'Cancelada' para 'Cancelada'
        ELSE NULL -- demais casos, NULL. (Acho que não pode ter NULL!!!! Mas NULL não deve ocorrer pois confirmei no banco que só há casos 4 e 5)
    END AS VIB_SVI_CD,  -- VIB_SVI_CD
  v.NUMEROPROTON -- VIB_NU_RELVISTORIA
FROM STG_TBVISTORIA v
JOIN TEMP_CAMPANHA_MAP m
  ON v.IDVISTORIA = m.IDVISTORIA
JOIN STG_VW_BDBARRAGEM b
  ON v.IDBARRAGEM = b.IDBARRAGEM
LEFT JOIN SNISSBARRAGENS.SNBFT_BARRAGEM@ORAHMG_LINK n
  ON b.CODIGO_SNISB = n.BAR_CD_SNISB
WHERE NOT EXISTS (
  SELECT 1 FROM FISCALIZACAO_MIGRACAO.FISTB_VISTORIA_BARRAGEM b2
   WHERE b2.VIB_NU = v.IDVISTORIA
);

-- 3. Insere TbOcorrencia em FISTB_OCORRENCIA
INSERT INTO FISCALIZACAO_MIGRACAO.FISTB_OCORRENCIA_TEMP (
  OCO_CD,
  OCO_EMI_CD,
  OCO_EMR_CD,
  OCO_TOC_CD,
  OCO_TX_EMPREENDIMENTOMOMENTO,
  OCO_DT_OCORRENCIA,
  OCO_IC_TEMPROCESSO,
  OCO_NU_PROCESSO,
  OCO_TSO_CD,
  OCO_NU_PROTOCOLO,
  OCO_DT_RECEBIMENTOAR,
  OCO_DT_VENCIMENTOOCORRENCIA,
  OCO_IC_MIGRADO,
  OCO_NU_MINUTA,
  OCO_DT_VENCIMENTOORIGINAL,
  OCO_IC_EXCLUIDO,
  OCO_BAR_CD
)
SELECT
  FISSQ_OCORRENCIA.NEXTVAL, -- OCO_CD
  NULL, -- OCO_EMI_CD (Empreendimento Irregular)
  NULL, -- OCO_EMR_CD (Empreendimento Regular)
  1, -- OCO_TOC_CD (Tipo Ocorrencia): 1. Instrumento Fiscalização; 2. Demandas de Fiscalização
  NULL, -- OCO_TX_EMPREENDIMENTOMOMENTO
  s.OCORRENCIADATAINICIO, -- OCO_DT_OCORRENCIA
  CASE WHEN s.OCORRENCIANUMEROPROCESSO IS NOT NULL THEN 1 ELSE 0 END, -- OCO_IC_TEMPROCESSO
  s.OCORRENCIANUMEROPROCESSO, -- OCO_NU_PROCESSO
  CASE
        WHEN s.IDSITUACAOOCORRENCIA = 1 THEN 1 -- de 'Enviada' para 'Enviada'
        WHEN s.IDSITUACAOOCORRENCIA = 2 THEN 2 -- de 'Pendência Técnica' para 'Pendência Técnica/Aceita'
        WHEN s.IDSITUACAOOCORRENCIA = 3 THEN 3 -- de 'Suspensa' para 'Suspensa'
        WHEN s.IDSITUACAOOCORRENCIA = 4 THEN 4 -- de 'Cancelada' para 'Cancelada/Negada'
        WHEN s.IDSITUACAOOCORRENCIA = 5 THEN 5 -- de 'Concluída/Arquivada' para 'Concluída'
        WHEN s.IDSITUACAOOCORRENCIA = 6 THEN 6 -- de 'Sem Pend. Téc. (Pend. Financeira)' para 'Sem Pend. Téc. (Pend. Financeira)'
        WHEN s.IDSITUACAOOCORRENCIA = 7 THEN 8 -- Verificar com fábio a obs. 'verificar' no De-Para para ocorrencia 7: de 'Aguardando Cadastro Proton' para 'Em edição'. Confirmado com Josimar.
        ELSE NULL -- demais casos, NULL. (Confirmado com Josimar, não pode ter NULL!!!! Verificar no banco todos os casos de IdSituacaoOcorrencia)
    END AS OCO_TSO_CD, -- OCO_TSO_CD
  NULL, -- OCO_NU_PROTOCOLO
  NULL, -- OCO_DT_RECEBIMENTOAR
  NULL, -- OCO_DT_VENCIMENTOOCORRENCIA
  1, -- OCO_IC_MIGRADO
  NULL, -- OCO_NU_MINUTA
  NULL, -- OCO_DT_VENCIMENTOORIGINAL
  0, -- OCO_IC_EXCLUIDO
  n.BAR_CD -- OCO_BAR_CD
FROM STG_TBOCORRENCIA s
JOIN STG_VW_BDBARRAGEM b
  ON s.IDBARRAGEM = b.IDBARRAGEM
LEFT JOIN SNISSBARRAGENS.SNBFT_BARRAGEM@ORAHMG_LINK n
  ON b.CODIGO_SNISB = n.BAR_CD_SNISB
WHERE NOT EXISTS (
  SELECT 1 FROM FISCALIZACAO_MIGRACAO.FISTB_OCORRENCIA o
   WHERE o.OCO_NU_PROTOCOLO = s.OCORRENCIANUMERODOC
);

-- 4. Gera um registro em FISTB_INSTRUMENTOFISCALIZACAO linkando
--    campanha, vistoria e ocorrência usando o CAM_CD mapeado na
--    tabela temporária.
INSERT INTO FISCALIZACAO_MIGRACAO.FISTB_INSTRUMENTOFISCALIZACAO_TEMP (
  AUI_CD,
  AUI_OCO_CD,
  AUI_TAL_CD,
  AUI_TPR_CD,
  AUI_CAM_CD,
  AUI_CD_REFERENCIA,
  AUI_DS_SITUACAO,
  AUI_DS_NOTIFICADOA,
  AUI_VL_PRAZOPROVIDENCIA,
  AUI_IC_PRAZOIMEDIATO,
  AUI_NU_LOCAL_IBGEMUNICIPIO,
  AUI_NM_SERVIDOR,
  AUI_NU_SIAPE,
  AUI_NU_AUTOINFRACAO,
  AUI_IC_LAVRADOEMCAMPO,
  AUI_NU_RASTREAMENTOAR,
  AUI_IC_ASSOCIADOCAMPANHA,
  AUI_DT_RECEBIMENTOAR,
  AUI_NU_DOCUMENTOREFERENCIA,
  AUI_IC_VINCULACAOAUIANTERIOR,
  AUI_TIF_CD,
  AUI_SER_CD,
  AUI_NU_LACRE,
  AUI_TIR_CD,
  AUI_NU_CPF_SERVIDOR,
  AUI_NU_INSTRUMENTO,
  AUI_DT_LAVRATURA,
  AUI_IC_ATENUANTE,
  AUI_IC_AGRAVANTE,
  AUI_IC_TEXTOUM,
  AUI_IC_TEXTODOIS,
  AUI_IC_TEXTOTRES,
  AUI_IC_TEXTOQUATRO,
  AUI_IC_TEXTOCINCO,
  AUI_IC_TEXTUM,
  AUI_IC_TEXTDOIS,
  AUI_IC_TEXTTRES,
  AUI_IC_TEXTQUATRO,
  AUI_IC_TEXTCINCO,
  AUI_IC_TEXTSEIS,
  AUI_IC_TEXTSETE,
  AUI_IC_TEXTOITO,
  AUI_IC_TEXTNOVE,
  AUI_IC_TEXTDEZ
)
SELECT
  FISSQ_INSTRUMENTOFISCALIZACAO.NEXTVAL, -- AUI_CD
  o.OCO_CD, -- AUI_OCO_CD (Id da ocorrencia FISTB_OCORRENCIA)
  NULL, -- AUI_TAL_CD
  CASE
    WHEN s.IDTIPOOCORRENCIA = 1 THEN 1 -- de 'AI - Advertência' para 'Advertência'
    WHEN s.IDTIPOOCORRENCIA = 2 THEN 2 -- de 'AI  - Multa Simples' para 'Multa Simples'
    WHEN s.IDTIPOOCORRENCIA = 3 THEN 3 -- de 'AI  - Multa Diária' para 'Multa Diária'
    WHEN s.IDTIPOOCORRENCIA = 4 THEN 4 -- de 'AI - Embargo Provisório' para 'Embargo Provisório'
    WHEN s.IDTIPOOCORRENCIA = 24 THEN 5 -- de 'AI - Embargo Definitivo' para 'Embargo Definitivo'
    ELSE NULL -- demais casos, NULL. Casos não atendidos até agora: 25 Notificação, 5 Solic. Providências/Informação, 7 Protocolo Emergência
  END AS AUI_TPR_CD, -- AUI_TPR_CD
  m.CAM_CD, -- AUI_CAM_CD
  s.OCORRENCIANUMERODOCREF, -- AUI_CD_REFERENCIA
  SUBSTR(s.OCORRENCIAPROVIDENCIAS,1,2000), -- AUI_DS_SITUACAO
  SUBSTR(s.OCORRENCIADESCRICAO,1,2000), -- AUI_DS_NOTIFICADOA
  s.OCORRENCIAPRAZO, -- AUI_VL_PRAZOPROVIDENCIA
  0, -- AUI_IC_PRAZOIMEDIATO
  NULL, -- AUI_NU_LOCAL_IBGEMUNICIPIO
  NULL, -- AUI_NM_SERVIDOR
  NULL, -- AUI_NU_SIAPE
  1, -- AUI_NU_AUTOINFRACAO (OcorrenciaNumeroDoc ???)
  1, -- AUI_IC_LAVRADOEMCAMPO (Toda a importação vai ser auto lavrado em campo)
  s.OCORRENCIANUMEROAR, -- AUI_NU_RASTREAMENTOAR
  0, -- AUI_IC_ASSOCIADOCAMPANHA
  s.OCORRENCIADATAINICIO, -- AUI_DT_RECEBIMENTOAR
  NULL, -- AUI_NU_DOCUMENTOREFERENCIA
  NULL, -- AUI_IC_VINCULACAOAUIANTERIOR
  NULL, -- AUI_TIF_CD
  NULL, -- AUI_SER_CD
  NULL, -- AUI_NU_LACRE
  NULL, -- AUI_TIR_CD
  NULL, -- AUI_NU_CPF_SERVIDOR
  NULL, -- AUI_NU_INSTRUMENTO
  NULL, -- AUI_DT_LAVRATURA
  NULL, -- AUI_IC_ATENUANTE
  NULL, -- AUI_IC_AGRAVANTE
  NULL, -- AUI_IC_TEXTOUM
  NULL, -- AUI_IC_TEXTODOIS
  NULL, -- AUI_IC_TEXTOTRES
  NULL, -- AUI_IC_TEXTOQUATRO
  NULL, -- AUI_IC_TEXTOCINCO
  NULL, -- AUI_IC_TEXTUM
  NULL, -- AUI_IC_TEXTDOIS
  NULL, -- AUI_IC_TEXTTRES
  NULL, -- AUI_IC_TEXTQUATRO
  NULL, -- AUI_IC_TEXTCINCO
  NULL, -- AUI_IC_TEXTSEIS
  NULL, -- AUI_IC_TEXTSETE
  NULL, -- AUI_IC_TEXTOITO
  NULL, -- AUI_IC_TEXTNOVE
  NULL  -- AUI_IC_TEXTDEZ
FROM STG_TBOCORRENCIA s
JOIN STG_TBVISTORIA v2
  ON s.IDVISTORIA = v2.IDVISTORIA
JOIN TEMP_CAMPANHA_MAP m
  ON v2.IDVISTORIA = m.IDVISTORIA
JOIN FISCALIZACAO_MIGRACAO.FISTB_OCORRENCIA o
  ON o.OCO_NU_PROTOCOLO = s.OCORRENCIANUMERODOC
LEFT JOIN STG_TBTECNICO t
  ON s.IDTECNICO = t.IDTECNICO
WHERE NOT EXISTS (
  SELECT 1 FROM FISCALIZACAO_MIGRACAO.FISTB_INSTRUMENTOFISCALIZACAO i
   WHERE i.AUI_OCO_CD = o.OCO_CD
);
